development:
  adapter: postgresql
  database: bar_dev
  min_messages: warning
  
  # uncomment these lines if you are connected to postgres over the network stack
  # host: localhost
  # username:
  # password:

test:
  adapter: postgresql
  database: bar_test
  min_messages: warning

  # uncomment these lines if you are connected to postgres over the network stack
  # host: localhost
  # username:
  # password:
